### ISSUE TITLE
REQUEST: Adding JIT to Artic

### ISSUE THREAD

**Issue by DennisRutjes** [AnyDSL/artic#1]
I am fiddling with the Impala JIT, is JIT also going to be present in artic? Maybe a rewrite of anydsl/runtime ?
Going to try to implement a REPL based on Impala or should I wait for Artic.

With kind regards,

Dennis

**Comment by madmann91** [comment]
Right now, we're working on ironing the bugs out and making sure existing applications can be compiled with artic, but porting the JIT (in the runtime) to artic is one of the things we'll tackle next (in the coming weeks, I suppose).
In the long run, the plan is to port everything to artic, so this means we'll progressively stop supporting Impala.

**Comment by madmann91** [comment]
We actually managed to port the runtime to artic. Just use the `artic` branch: https://github.com/AnyDSL/runtime/tree/artic . If you encounter any issue with the port, just create an issue on the runtime page, or here if it's related to artic.
