### ISSUE TITLE
self-referential struct crashes compiler

### ISSUE THREAD

**Issue by michael-kenzel** [AnyDSL/artic#13]
the following code will reproduce the issue (segfault) when compiled with `--emit-llvm`:
```rust
#[import(cc = "thorin")]
fn cuda(i32, (i32, i32, i32), (i32, i32, i32), fn () -> ()) -> ();

struct Queue {
  next: &mut Queue,
  size: i32
}

#[export]
fn test() {
  let queue = 42 as &mut addrspace(1) Queue;

  cuda(0, (1, 1, 1), (1, 1, 1), @|| {
    queue.size = 0;
  });
}
```

**Comment by Hugobros3** [comment]
I messed that up when merging the HLS branch. I pushed a hotfix: https://github.com/AnyDSL/thorin/commit/070da6b84a53a94336344c553190df80c5603c74

**Comment by michael-kenzel** [comment]
yeah that seems to do the trick, thanks!
