### ISSUE TITLE
--print-ast does not handle escape sequences in character literals correctly

### ISSUE THREAD

**Issue by michael-kenzel** [AnyDSL/artic#8]
When faced with character literals that contain escape sequences, `--print-ast` fails to correctly escape these escape sequences before printing them out, resulting in output that is not valid Artic.

for example:
```rust
print_char('\n');
```
will be turned into
```rust
print_char('
');
```

**Comment by madmann91** [comment]
Is this fixed? Can this issue be closed?

**Comment by Hugobros3** [comment]
I think so

**Comment by michael-kenzel** [comment]
I just ran into this again, so I'm afraid it doesn't seem to be fixed…
